fix: Remove extraneous 'helloworld' line from InvoiceGenerator component

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,10 @@
 # .husky/pre-commit
 prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
 git update-index --again
+
+
+npx eslint $(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx)$') --max-warnings=0
+if [ $? -ne 0 ]; then
+  echo "\n Lint errors found. Commit aborted."
+  exit 1
+fi
